### ISSUE TITLE
Limit

### ISSUE THREAD

**Issue by wimmelstein** [TLaMars/S2.4-Java-Advanced#1]
Hoi Thomas.

Ziet er heel goed uit. Een puntje dat ik graag wil aanstippen:

return applesStream
                .limit(pageSize)
                .collect(Collectors.toList());

Een pageSize suggereert dat je bijvoorbeeld bij 20 elementen met een pageSize van 5 je 4 pagina's teruggeeft met vijf elementen. Dat is hier niet het geval. Je geeft een lijst terug met een totale grootte van 5. De andere 15 elementen geef je niet terug.

Als je een pageSize wilt intoduceren zou ik kijken naar Pageable List, maar daar komen we hopelijk wel aan toe als we de database gaan introduceren.

Als je niet pageSize bedoelde, maar maximum aantal elementen, dan zou ik de variabele maxElements of maxSize noemen.

Met vriendelijke groet,
Wim Wiltenburg

**Comment by TLaMars** [comment]
Hoi Wim,

Bedankt voor de feedback. 
Ik heb het zojuist aangepast van pageSize naar maxApples.

Groetjes,
Thomas
